CHORE: rollback logic & add chmod

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -112,8 +112,27 @@ jobs:
           echo "DOCKER_REPO is: $DOCKER_REPO"
           
           # Copy the .env.prod file to the EC2 instance
-           # echo "$ENV_PROD" > .env.prod
-           # scp -o StrictHostKeyChecking=no -i private_key.pem .env.prod $EC2_USER@$EC2_HOST:/home/$EC2_USER/$APP_NAME/envs/.env.prod
+          echo "$ENV_PROD" > .env.prod
+          scp -o StrictHostKeyChecking=no -i private_key.pem .env.prod $EC2_USER@$EC2_HOST:/home/$EC2_USER/$APP_NAME/envs/.env.prod
+          
+          # Ensure the envs directory exists
+          mkdir -p envs
+          
+          # List files to verify that .env.prod was created
+          echo "Listing files in envs directory to verify .env.prod existence:"
+          ls -la envs/
+
+          # verify .env.prod file existence
+          cd envs
+          if [ -f envs/.env.prod ]; then
+           echo ".env.prod file exists."
+           chmod 600 envs/.env.prod
+           cat envs/.env.prod   # Optional: Show the contents of the file for verification
+          else
+           echo "Error: .env.prod file does not exist."
+           exit 1  # Exit with an error code to fail the workflow
+           fi
+
 
           # Ensure the envs directory exists
           # ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "mkdir -p /home/$EC2_USER/$APP_NAME/envs"
@@ -127,13 +146,14 @@ jobs:
           # ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "ls -la /home/$EC2_USER/$APP_NAME/envs/"
 
           # SSH into the EC2 instance and deploy the Docker container
+          cd ..
           ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
             cd /home/$EC2_USER/$APP_NAME
 
             # Pull the latest Docker image
             FULL_IMAGE_REFERENCE="$DOCKER_REPO/$APP_NAME:latest"
             echo "Full image reference: $FULL_IMAGE_REFERENCE"
-            # docker pull $DOCKER_REPO/$APP_NAME:latest
+            docker pull $DOCKER_REPO/$APP_NAME:latest
 
             echo "Pulling Docker image from Docker Hub..."
             docker pull $FULL_IMAGE_REFERENCE
@@ -154,8 +174,7 @@ jobs:
           # Clean up sensitive files
           rm private_key.pem
           
-          # Ensure the envs directory exists
-           # mkdir -p envs
+          
           
           # Set permissions to ensure Docker can access the file
            # echo "Setting permissions on .env.prod..."
@@ -163,20 +182,6 @@ jobs:
            #chmod 755 envs
 
 
-
-          # List files to verify that .env.prod was created
-           # echo "Listing files in envs directory to verify .env.prod existence:"
-           # ls -la envs/
-
-          # verify .env.prod file existence
-          # cd envs
-          # if [ -f envs/.env.prod ]; then
-            # echo ".env.prod file exists."
-            # cat envs/.env.prod   # Optional: Show the contents of the file for verification
-          # else
-            # echo "Error: .env.prod file does not exist."
-            # exit 1  # Exit with an error code to fail the workflow
-            # fi
 
           # SSH into the EC2 instance and deploy the Docker container
           # cd ..
